"""The shared lookup substrate (DESIGN §6.6, milestone M1).

Four questions later in the pipeline — how easily does this donor activate (C5), how big
a barrier does this step face (C6), does this metal suit this donor (C7), and where did
those numbers come from (C8) — all want the same handful of tabulated facts.  Building
one table they share is cheaper than three bespoke calculations, and it means a number
can be corrected in one place.

**C8, resolved: the two halves are sourced differently on purpose.**

* `donor_descriptors.tsv` is **curated by hand**.  Aqueous pKa is context-dependent and
  no package covers these donor classes; every row names the class of reference it came
  from, and rows that are chemical judgement say `estimate` rather than borrowing a
  citation they do not have.
* `metal_descriptors.tsv` is **generated** by `scripts/build_metal_descriptors.py` from
  `mendeleev`, whose version is written into every row.  Shannon radii are standard and
  tedious; HSAB class, preferred CN and exchange lability are not in any package and are
  curated inside that generator.

Two things this module refuses to do, both of them ground rule 8 in miniature:

* **`donor()` and `metal()` raise on an unknown key.**  Returning a neutral default would
  make a missing row indistinguishable from a real measurement, and the caller would be a
  screening loop that quietly scores an unknown donor as average.
* **A row with no `source` is rejected at load.**  Ground rule 3 says no bare floats; a
  pKa with no provenance is a bare float wearing a column name.

`live_dof` is NOT stored in the TSV even though the schema has the column.  It is defined
by `sites.frames.live_dof()`, so it is read from there at load time and written into the
database as a projection.  A test asserts the two still agree — one home for the torsion
model, and a stored copy for anyone querying SQL directly.
"""
from __future__ import annotations

import csv
from collections.abc import Iterable
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Literal

from mofsbu._types import MofsbuError
from mofsbu.config import REPO_ROOT
from mofsbu.sites.frames import LiveDOF, live_dof
from mofsbu.versions import ALGO_VERSIONS

HSAB = Literal["hard", "borderline", "soft"]
Lability = Literal["fast", "moderate", "slow"]

TABLE_DIR = REPO_ROOT / "data" / "reference"
DONOR_TSV = TABLE_DIR / "donor_descriptors.tsv"
METAL_TSV = TABLE_DIR / "metal_descriptors.tsv"

_HSAB_VALUES = {"hard", "borderline", "soft"}
_LABILITY_VALUES = {"fast", "moderate", "slow"}


class UnknownDescriptor(MofsbuError):
    """Asked for a donor type or an ion the table does not cover.

    Deliberately loud.  The alternative — a default row — turns "we have never
    characterised this donor" into a number that looks exactly like every other number.
    """


class DescriptorTableError(MofsbuError):
    """A descriptor file is malformed, or a row arrived without provenance."""


# ── records ──────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class DonorDescriptor:
    donor_type: str
    pka: float | None                 # None = neutral donor, no activation step
    pka_sigma: float | None
    hsab: HSAB
    default_denticity: int
    live_dof: LiveDOF
    source: str
    source_version: str

    @property
    def needs_activation(self) -> bool:
        """Does using this donor require removing a proton first?

        The whole reason `pka` is allowed to be None.  A pyridyl nitrogen is a donor as
        it stands; a carboxylic acid is not until it loses its proton.
        """
        return self.pka is not None


@dataclass(frozen=True)
class MetalDescriptor:
    symbol: str
    charge: int
    ionic_radius: float | None        # angstrom, Shannon, at preferred_cn[0]
    hsab: HSAB
    preferred_cn: tuple[int, ...]
    d_electrons: int | None           # None for main-group ions
    exchange_lability: Lability
    source: str
    source_version: str


# ── loading ──────────────────────────────────────────────────────────────────


def _rows(path: Path) -> Iterable[dict[str, str]]:
    if not path.exists():
        raise DescriptorTableError(
            f"{path} is missing. The donor table is tracked in git; the metal table is "
            f"generated by scripts/build_metal_descriptors.py.")
    with path.open(encoding="utf-8") as fh:
        body = [line for line in fh if not line.startswith("#")]
    yield from csv.DictReader(body, delimiter="\t")


def _optional_float(value: str, *, field: str, key: str) -> float | None:
    text = (value or "").strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        raise DescriptorTableError(f"{key}: {field}={value!r} is not a number") from None


def _checked_hsab(value: str, key: str) -> HSAB:
    text = (value or "").strip()
    if text not in _HSAB_VALUES:
        raise DescriptorTableError(
            f"{key}: hsab={value!r} is not one of {sorted(_HSAB_VALUES)}")
    return text                                                          # type: ignore[return-value]


@lru_cache(maxsize=1)
def donor_table(path: Path | None = None) -> dict[str, DonorDescriptor]:
    out: dict[str, DonorDescriptor] = {}
    for row in _rows(path or DONOR_TSV):
        key = row["donor_type"].strip()
        if not key:
            continue
        source = (row.get("source") or "").strip()
        if not source:
            raise DescriptorTableError(
                f"{key}: no source. A pKa with no provenance is a bare float wearing a "
                f"column name (ground rule 3); write `estimate` if that is what it is.")
        pka = _optional_float(row.get("pka", ""), field="pka", key=key)
        sigma = _optional_float(row.get("pka_sigma", ""), field="pka_sigma", key=key)
        if pka is not None and sigma is None:
            raise DescriptorTableError(
                f"{key}: has a pKa and no pka_sigma. The spread is not optional — it is "
                f"what stops a curated estimate being read as a measurement.")
        out[key] = DonorDescriptor(
            donor_type=key, pka=pka, pka_sigma=sigma,
            hsab=_checked_hsab(row.get("hsab", ""), key),
            default_denticity=int(row.get("default_denticity") or 1),
            live_dof=live_dof(key),                 # from frames, never duplicated here
            source=source, source_version=ALGO_VERSIONS["descriptor_tables"])
    if not out:
        raise DescriptorTableError(f"{path or DONOR_TSV} has no rows")
    return out


@lru_cache(maxsize=1)
def metal_table(path: Path | None = None) -> dict[tuple[str, int], MetalDescriptor]:
    out: dict[tuple[str, int], MetalDescriptor] = {}
    for row in _rows(path or METAL_TSV):
        symbol = row["symbol"].strip()
        if not symbol:
            continue
        charge = int(row["charge"])
        key = f"{symbol}{charge:+d}"
        source = (row.get("source") or "").strip()
        if not source:
            raise DescriptorTableError(f"{key}: no source")
        lability = (row.get("exchange_lability") or "").strip()
        if lability not in _LABILITY_VALUES:
            raise DescriptorTableError(
                f"{key}: exchange_lability={lability!r} is not one of "
                f"{sorted(_LABILITY_VALUES)}")
        d = (row.get("d_electrons") or "").strip()
        out[(symbol, charge)] = MetalDescriptor(
            symbol=symbol, charge=charge,
            ionic_radius=_optional_float(row.get("ionic_radius", ""),
                                         field="ionic_radius", key=key),
            hsab=_checked_hsab(row.get("hsab", ""), key),
            preferred_cn=tuple(int(c) for c in row["preferred_cn"].split(",") if c),
            d_electrons=int(d) if d else None,
            exchange_lability=lability,                                  # type: ignore[arg-type]
            source=source, source_version=(row.get("source_version") or "").strip())
    if not out:
        raise DescriptorTableError(f"{path or METAL_TSV} has no rows")
    return out


# ── lookup ───────────────────────────────────────────────────────────────────


def donor(donor_type: str) -> DonorDescriptor:
    """Descriptors for a donor type, or a refusal naming what is missing."""
    try:
        return donor_table()[donor_type]
    except KeyError:
        raise UnknownDescriptor(
            f"no descriptor row for donor type {donor_type!r}. Every type "
            f"`sites.perception` can emit needs one — add it to "
            f"data/reference/donor_descriptors.tsv with its source.") from None


def metal(symbol: str, charge: int) -> MetalDescriptor:
    """Descriptors for an ion, or a refusal naming what is missing."""
    try:
        return metal_table()[(symbol, charge)]
    except KeyError:
        raise UnknownDescriptor(
            f"no descriptor row for {symbol}{charge:+d}. Add it to the CURATED table in "
            f"scripts/build_metal_descriptors.py and regenerate — the TSV is output, not "
            f"a place to type into.") from None


def known_donor_types() -> frozenset[str]:
    return frozenset(donor_table())


def known_ions() -> frozenset[tuple[str, int]]:
    return frozenset(metal_table())


# ── into the registry ────────────────────────────────────────────────────────


def sync_to_registry(reg, *, donors: bool = True, metals: bool = True) -> tuple[int, int]:
    """Write both tables into `donor_descriptors` / `metal_descriptors`.

    Idempotent: the tables are lookup data keyed by their own natural keys, so a re-sync
    after a correction replaces rows rather than accumulating them.  Returns the counts
    written, because "it silently wrote nothing" and "it worked" should not look alike.
    """
    n_donor = n_metal = 0
    if donors:
        for d in donor_table().values():
            reg.conn.execute(
                "INSERT OR REPLACE INTO donor_descriptors (donor_type, pka, pka_sigma, "
                "hsab, default_denticity, live_dof, source, source_version) "
                "VALUES (?,?,?,?,?,?,?,?)",
                (d.donor_type, d.pka, d.pka_sigma, d.hsab, d.default_denticity,
                 d.live_dof.value, d.source, d.source_version))
            n_donor += 1
    if metals:
        for m in metal_table().values():
            reg.conn.execute(
                "INSERT OR REPLACE INTO metal_descriptors (symbol, charge, ionic_radius, "
                "hsab, preferred_cn, d_electrons, exchange_lability, source, "
                "source_version) VALUES (?,?,?,?,?,?,?,?,?)",
                (m.symbol, m.charge, m.ionic_radius, m.hsab,
                 ",".join(str(c) for c in m.preferred_cn), m.d_electrons,
                 m.exchange_lability, m.source, m.source_version))
            n_metal += 1
    return n_donor, n_metal
